### ISSUE TITLE
Non async boto3 calls blocking main thread

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent-awslambda-plugin#37]
## Description

As the executors are intended to be async-aware they are expected to use asynchronous calls for i/o bound operations, currently the official AWS SDK client `boto3` only performs synchronous / blocking calls when interacting with Amazon services. 

As this executor utilizes `boto3` for making requests to AWS services (such as uploading function files, ect.) it currently blocks the main thread affecting parallelization and increasing latency to the covalent server (also viewing the UI). Hence we will need to leverage other client libs that support asyncio like `aioboto3` and extend them if necessary.

**Comment by cjao** [comment]
I think most of the boto3 calls in this executor have been moved off the main thread except for those in teardown.
