### ISSUE TITLE
Adapt executor to use a pre-defined container-based Lambda function

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent-awslambda-plugin#46]
We need to write a Dockerfile to create a container image according to the [Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html),  and adapt `awslambda.py` to use a user-specified Lambda function for all tasks. This function should reference a pre-built container image and is intended to be provisioned in advance together with the other cloud resources.

These steps are somewhat intertwined because there is no way to test the modified executor without a working container image.

### Acceptance criteria:
- [x] The executor accepts the name of an existing Lambda function in its constructor.
- [x] `run()` simply uploads the task inputs and invokes the pre-defined Lambda function, passing variable task metadata in the event payload.
- [x] `setup()` and `teardown()` are removed together with all references to deployment archives and lambda function creation.
- [x] The Dockerfile defines an image that can be used as a Lambda runtime. In addition, the Lambda handler script should be aware of the conventions used to pass task metadata in the event payload.
- [x] Unit tests are updated.

**Comment by venkatBala** [comment]
PR: https://github.com/AgnostiqHQ/covalent-awslambda-plugin/pull/50
